# Generated by Django 2.2 on 2020-02-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneLine', '0002_auto_20200225_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
    ]
